FROM nvidia/cuda:11.1.1-cudnn8-runtime-ubuntu20.04
ARG DEBIAN_FRONTEND=noninteractive

#  docker build  -f Dockerfile_Ubuntu_18_04 -t bleh:1 .


ENV CUDNN_VERSION=8.0.5.39-1+cuda11.1
ENV NCCL_VERSION=2.8.4-1+cuda11.1
ENV CUDA_VERSION=11.1


RUN apt-get update && apt-get install -y --allow-change-held-packages --no-install-recommends apt-utils \
        build-essential \
        cmake \
        g++ \
        git \
        curl \
        vim \
        wget \
        ca-certificates \
        cuda-toolkit-${CUDA_VERSION} \
        libcudnn8=${CUDNN_VERSION} \
        libnccl2=${NCCL_VERSION} \
        libnccl-dev=${NCCL_VERSION} \
        libjpeg-dev \
        libpng-dev \
        libsm6 \
        libxext6 \
        libxrender-dev \
        aria2 \
    	  librdmacm1 \
        libibverbs1 \
        ibverbs-providers && \
        rm -rf /var/lib/apt/lists/*


RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-2020.11-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh

RUN /opt/conda/bin/conda update -y --all && \
    /opt/conda/bin/conda install -c anaconda gxx_linux-64 && \
    /opt/conda/bin/conda clean -ya

ENV PATH /opt/conda/bin:$PATH

# This must be done before pip so that requirements.txt is available

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

WORKDIR /workspace
RUN chmod -R a+w /workspace
