FROM nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04
#  docker build  -f Dockerfile_Ubuntu_18_04 -t bleh:1 .

RUN apt-get update && apt-get install -y --allow-change-held-packages --no-install-recommends apt-utils \
        build-essential \
        cmake \
        g++-4.8 \
        git \
        curl \
        vim \
        wget \
        ca-certificates \
        libnccl2 \
        libnccl-dev \
        libjpeg-dev \
        libpng-dev \
        libsm6 \
        libxext6 \
        libxrender-dev \
        aria2 \
    	  librdmacm1 \
        libibverbs1 \
        ibverbs-providers && \
        rm -rf /var/lib/apt/lists/*


RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-2020.11-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh

RUN /opt/conda/bin/conda update -y --all && \
    /opt/conda/bin/conda install -c anaconda gxx_linux-64 && \
    /opt/conda/bin/conda clean -ya

ENV PATH /opt/conda/bin:$PATH

# This must be done before pip so that requirements.txt is available

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

WORKDIR /workspace
RUN chmod -R a+w /workspace
